export const weatherDescriptions : any = {
  "thunderstorm with light rain": "Tempestade com chuva fraca",
  "thunderstorm with rain": "Tempestade com chuva",
  "thunderstorm with heavy rain": "Tempestade com chuva intensa",
  "light thunderstorm": "Chuva fraca",
  thunderstorm: "Chuva",
  "heavy thunderstorm": "Chuva intensa",
  "ragged thunderstorm": "Tempestade irregular",
  "thunderstorm with light drizzle": "Tempestade com garoa fraca",
  "thunderstorm with drizzle": "Tempestade com garoa",
  "thunderstorm with heavy drizzle": "Tempestade com garoa intensa",

  "light intensity drizzle": "Chuvisco de intensidade fraca",
  drizzle: "Chuvisco",
  "heavy intensity drizzle": "Chuvisco de intensidade forte",
  "light intensity drizzle rain": "Chuvisco de intensidade fraca com chuva",
  "drizzle rain": "Chuvisco com chuva",
  "heavy intensity drizzle rain": "Chuvisco de intensidade forte com chuva",
  "shower rain and drizzle": "Chuva fraca e chuvisco",
  "heavy shower rain and drizzle": "Chuva forte e chuvisco",
  "shower drizzle": "Chuvisco de chuva",

  "light rain": "Chuva fraca",
  "moderate rain": "Chuva moderada",
  "heavy intensity rain": "Chuva de intensidade forte",
  "very heavy rain": "Chuva muito forte",
  "extreme rain": "Chuva extrema",
  "freezing rain": "Chuva congelante",
  "light intensity shower rain": "Chuva fraca de chuvisco",
  "shower rain": "Chuva de chuvisco",
  "heavy intensity shower rain": "Chuva forte de chuvisco",
  "ragged shower rain": "Chuva irregular de chuvisco",

  "light snow": "Neve fraca",
  snow: "Neve",
  "heavy snow": "Neve intensa",
  sleet: "Granizo",
  "light shower sleet": "Chuvisco de granizo fraco",
  "shower sleet": "Chuvisco de granizo",
  "light rain and snow": "Chuva fraca e neve",
  "rain and snow": "Chuva e neve",
  "light shower snow": "Chuvisco de neve fraca",
  "shower snow": "Chuvisco de neve",
  "heavy shower snow": "Chuvisco intenso de neve",

  mist: "Neblina",
  smoke: "Fumaça",
  haze: "Névoa",
  "sand/dust whirls": "Redemoinhos de areia/poeira",
  fog: "Névoa",
  sand: "Areia",
  dust: "Poeira",
  "volcanic ash": "Cinzas vulcânicas",
  "squalls": "Rajinhas",
  "tornado": "Tornado",
  "clear sky": "Céu limpo",
  "few clouds": "Poucas nuvens: 11-25%",
  "scattered clouds": "Nuvens dispersas: 25-50%",
  "broken clouds": "Nuvens quebradas: 51-84%",
  "overcast clouds": "Nuvens nubladas: 85-100%",
};


const handleGetDescription = (param: string) => {
  
}
